### ISSUE TITLE
"Can't connect" error while uploading a new game build

### ISSUE THREAD

**Issue by ghost** [gamejolt/next-issue-tracker#1239] opened 2019-01-15 10:27 UTC
**How are you using Game Jolt?**
I'm using it to sell my game.

**Please describe the issue you are having**
As I'm trying to upload a new build of my game (.rar), I'm getting the "Can't connect" error.

1. Go to Packages, select the package you need to update
2. Create a new build, scroll down and select the file you want to upload, in my case a .rar archive.
3. Wait for it to upload
4. Wait for it to start processing
Now, after a while (while processing), it suddenly throws the error I mentioned.

It's very frustrating that I can't update my game!

Thanks for any possible fixes

**Comment by YLivay** [comment] 2019-04-15 07:21
Probably a duplicate of #1249 which is now fixed!

**Closed as completed by YLivay** 2019-04-15 07:21 UTC
