### ISSUE TITLE
Followed games number incorrect

### ISSUE THREAD

**Issue by Feargeorge** [gamejolt/next-issue-tracker#134] opened 2015-02-27 09:07 UTC
So, I was taking a look at the games I follow, and then I noticed this:

![](http://i.imgur.com/VVkQJbL.png)

I have counted the games myself and they were 11, not 12.

**Comment by hworld** [comment] 2015-02-27 16:30
You're following hidden games then. Duplicate of #104

**Closed by hworld** 2015-02-27 16:30 UTC
