### ISSUE TITLE
New messages do not get removed after being read

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/next-issue-tracker#137] opened 2015-02-27 18:09 UTC
I received in incoming personal chat message today.
It was properly marked on the new site, however when I opened it the indicator that this guy sent me one message didn't disappear until I renewed the entire page (this DOES happen on the old site).

My reply was properly sent through the new site as far as I could see on the old site where the reply appeared as well (and the new message indicator disappeared there as well after I read the message through the new site).

**Comment by NikSudan** [comment] 2015-02-27 18:17
Duplicate of #94

**Closed by NikSudan** 2015-02-27 18:17 UTC
