### ISSUE TITLE
Table removal (due to getting rid of MarkDown) may have destroyed more stuff

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/next-issue-tracker#1307] opened 2019-07-10 15:17 UTC
![image](https://user-images.githubusercontent.com/11202073/60981365-79e31f00-a336-11e9-9a4e-8ab06270c0ab.png)

This used to be a table, and now see what mess it has been turned into? In the original setting the portrait pictures were nicely beside the text, due to the usage of tables... Why was that removed and turned into this? Undoubtedly this may have destroyed more game pages and devlogs....

**Comment by YLivay** [comment] 2019-07-10 15:47
Removing tables was a regression we were fully aware of. they were not meant to be used for styling but to display tabular data. Pages that were misusing tables would break, but we had to do that to get content editor out. Sorry but im closing this as a non issue.

**Comment by Tricky1975** [comment] 2019-07-10 15:48
![image](https://user-images.githubusercontent.com/11202073/60983832-f7109300-a33a-11e9-816b-ddfc883c3ee3.png)

**Comment by hworld** [comment] 2019-07-10 16:41
I want to give a little bit more information on this. It's not that people were "misusing tables." It's impossible for users to misuse something, unless they're deliberately trying to break the site. We gave a styling/content tool and people used it for all sorts of things.

The reason we removed tables is because _they're really really hard to do in an editor_. @nilllzz had actually gotten tables working within our new content editor, but there were so many bugs that it became almost unusable. We realized it would take another month of work just to support tables and decided that not enough people were using them to be worth it. The other thing we tried doing is making sure that the editor can be run easily on a phone. Tables are just so wide and complex that editing them on a phone was nearly impossible.

They may eventually come back, but for now I would suggest trying to figure out other ways to style the content on the page. For this specific example, it might look nice to remove them from the list they're in, and just put an image (that will center) and their bio below that image. It'll take up more space vertically, but it'll display well on more devices and be easy to edit for you in the future.

**Comment by Tricky1975** [comment] 2019-07-10 17:07
I've multiple pages like that, and tons of work, actually, so I'm not amused.... Perhaps allowing to markdown-escapes, could have done well... Oh well... Yeah, I do know how complex tables can be... I've been a webmaster back in the old days when using JavaScript was a big no-go area only used by show-offs, and I've worked a lot with tables back then. Now I'm not sure if the tables were used so little because they aren't a good feature, but rather that people didn't know about them...

**Comment by hworld** [comment] 2019-07-10 17:32
Wasn't telling you for your amusement. Was trying to give clarity on why a hard decision was decided the way it was. We went back and forth and tried a lot of options. We spent weeks of dev time on just tables. In the end, our team is just too small to continue supporting them. =\

**Closed as completed** 2019-07-10 17:32 UTC
