### ISSUE TITLE
Slideshow indicators don't update correctly sometimes

### ISSUE THREAD

**Issue by acidpoison** [gamejolt/next-issue-tracker#232] opened 2015-05-09 00:49 UTC
Sometimes I leave the homepage up (when I'm in chat and afk) and the slideshow displaying featured games will cycle through. On occasion, the dots at the bottom of the slideshow panel don't update to revert back to their unhighlighted form, making multiple dots appear white instead of just one white and others grey.

**Comment by hworld** [comment] 2015-05-09 00:56
Yeah, I've got this logged already. It also happens with the rating widget. It's because we're on a development version of angularjs that broke it all. I'm thinking they'll be releasing a fixed version in a few days.

Duplicate of #218

**Closed by hworld** 2015-05-09 00:56 UTC
