### ISSUE TITLE
"Game Developer" not shown when commenting own games.

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/next-issue-tracker#153] opened 2015-03-05 00:01 UTC
On the old site we can see all comments made on a game by the dev of that game him/herself that he/she is marked as "Game's developer". I missed that on the new site, and I think it would be handy if it's still there. Most comments I make myself on my own games are replies to what people posted and I think they like to see that I'm the dev so that there can be no doubt about it. After all whenever I answer something people ask about a game of mine we can deem that answer "official", right?

**Comment by NikSudan** [comment] 2015-03-07 11:09
Dupe of #86

**Closed by NikSudan** 2015-03-07 11:09 UTC
