### ISSUE TITLE
User gets an error page using Google Chrome on Windows Vista

### ISSUE THREAD

**Issue by NathanAuckett** [gamejolt/next-issue-tracker#1252] opened 2019-03-05 17:24 UTC
The title about sums it up. The user is on Windows Vista using the latest version of Google Chrome and gets this error message when trying to access the home page: https://prnt.sc/ly3eo6

A security Transport Security message was found in the browser console: https://prnt.sc/mt5krt

**Comment by YLivay** [comment] 2019-03-17 11:57
I'm pretty sure I answered a similar topic just a few days ago, might be duplicate.

Anyways, it seems like the user's browser or system is outdated and is not able to negotiate the SSL cipher algorithms. Try Windows Update + latest version of the browser and it should be good to go.

**Comment by qwertychouskie** [comment] 2019-03-18 20:09
The problem is that Chrome on Vista hasn't been supported in a long time, so the browser is probably quite old.  Firefox goes through 52.9.0esr on Vista, though even that might not work.  Not much can be done for such an old OS, if they want things to work they'll need Windows 7 or Linux, or a new computer.

**Comment by YLivay** [comment] 2019-04-15 07:13
@qwertychouskie thanks for the input.

Yeah, I think we'll close this issue, not much we can do about these cases sadly. Update and smell the Cortana in the air.

**Closed as completed by YLivay** 2019-04-15 07:13 UTC
